export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const ADMIN_SET_USERS = "ADMIN_SET_USERS";
export const ADMIN_FETCH_USER = "ADMIN_FETCH_USER";
export const ADMIN_SET_CATEGORIES = "ADMIN_SET_CATEGORIES";
export const ADMIN_SET_LISTINGS = "ADMIN_SET_LISTINGS";
export const ADMIN_SET_REPORTED_USERS = "ADMIN_SET_REPORTED_USERS";
export const ADMIN_SET_PRICING_MODELS = "ADMIN_SET_PRICING_MODELS"
